name: Laravel Docker-Compose CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Services
        run: docker-compose up -d

      - name: Wait for Database to be Ready
        run: |
          echo "Waiting for DB..."
          docker-compose exec -T app bash -c "
            until mysql -h db -u user_name -proot -e 'select 1'; do
              echo '⏳ Waiting for DB...'
              sleep 2
            done
          "
          echo "✅ Database is ready!"

      - name: Create .env File & App Key
        run: |
          docker-compose exec -T app cp .env.example .env || true
          docker-compose exec -T app php artisan key:generate
          docker-compose exec -T app chmod -R 777 storage bootstrap/cache

      - name: Install Dependencies
        run: docker-compose exec -T app composer install

      - name: Run Migrations & Tests
        run: |
          docker-compose exec -T app php artisan migrate --force
          docker-compose exec -T app php artisan test
        env:
          DB_HOST: db
          DB_DATABASE: laravel
          DB_USERNAME: user_name
          DB_PASSWORD: root